name: Galena Doc Watch

on:
  schedule:
    # Central Time slots (both DST and Standard):
    # 08:00 CT  -> 13:00 UTC (CDT), 14:00 UTC (CST)
    - cron: '0 13 * * *'   # 08:00 during CDT (UTC-5)
    - cron: '0 14 * * *'   # 08:00 during CST (UTC-6)
    # 10:00 CT  -> 15:00 / 16:00 UTC
    - cron: '0 15 * * *'   # 10:00 CDT
    - cron: '0 16 * * *'   # 10:00 CST
    # 12:00 CT  -> 17:00 / 18:00 UTC
    - cron: '0 17 * * *'   # 12:00 CDT
    - cron: '0 18 * * *'   # 12:00 CST
    # 14:00 CT  -> 19:00 / 20:00 UTC
    - cron: '0 19 * * *'   # 14:00 CDT
    - cron: '0 20 * * *'   # 14:00 CST
    # 16:00 CT  -> 21:00 / 22:00 UTC
    - cron: '0 21 * * *'   # 16:00 CDT
    - cron: '0 22 * * *'   # 16:00 CST
    # 17:00 CT  -> 22:00 / 23:00 UTC
    - cron: '0 22 * * *'   # 17:00 CDT
    - cron: '0 23 * * *'   # 17:00 CST
  workflow_dispatch:
    inputs:
      force_body:
        description: 'Optional: Updated or Not updated (manual test)'
        required: false
        default: ''

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npx playwright install --with-deps chromium
      - name: Run checker
        env:
          TARGET_URL: https://www.cityofgalenapark-tx.gov/DocumentCenter/Index/69
          RECIPIENTS: mark@electriqo.pro
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_SECURE: ${{ secrets.SMTP_SECURE }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_FROM: ${{ secrets.SMTP_FROM }}
          FORCE_BODY: ${{ github.event.inputs.force_body || '' }}
        run: node check.js
      - name: Commit state
        uses: EndBug/add-and-commit@v9
        with:
          add: 'state.json'
          message: 'chore: update state'
          default_author: github_actions
